version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "devel"

  - package-ecosystem: "bundler"
    directory: "/plaac/web"
    schedule:
      interval: "weekly"
    target-branch: "devel"
