name: PLAAC docker web container build

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/web-container.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: whitehead/plaac-web

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Determine PLAAC version
        id: version
        run: |
          VERSION=$(./cli/get_plaac_version.sh)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "PLAAC Version: $VERSION"
          
      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./
          file: ./web/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PLAAC_VERSION=${{ steps.version.outputs.version }}          
          cache-from: type=gha
          cache-to: type=gha,mode=max
