name: Web UI CI

on:
  push:
    paths-ignore: &plaac_web_paths
      - '.gitignore'
      - '.github/dependabot.yml'
      - '.github/workflows/cli.yml'
      - '.github/workflows/web-container.yml'      
      - '**/*.md'
      - 'cli/build_background_files.py'
      - 'cli/example/generate_example_output.sh'
      - 'cli/example/generate_scer_spreadsheet.sh'
      - 'cli/example/visualize_example_output.sh'
      - 'web/bin/fancy-yeast-spreadsheet.py'
  pull_request:
    paths-ignore:
      &plaac_web_paths

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RACK_ENV: test
    defaults:
      run:
        working-directory: web

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      # 2. Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2  # match your local Ruby version
          bundler-cache: true

      # 3. Install Java for PLAAC
      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4. Build PLAAC CLI JAR
      - name: Build PLAAC JAR
        run: |
          cd ../cli
          ./build_plaac.sh
          cp target/plaac.jar ../web/bin/plaac.jar

      # 5. Install Ruby gems
      - name: Install gems
        run: bundle install --jobs 4 --retry 3

      # 6. Run integration tests
      - name: Run integration specs
        run: |
           mkdir -p logs
           mkdir -p tmp
           bundle exec rspec spec/integration/plaac_web_spec.rb --format documentation
          
