source "https://rubygems.org"

gem 'eventmachine', '~> 1.0.9.1'

# framework
gem 'sinatra', '~> 4.2'
gem 'sinatra-extension', '~> 1.0'
gem 'sinatra-contrib', '~> 4.2'
gem 'rackup', '~> 2.2'

# Gemfile
gem 'activesupport', '~> 8.1'

# view
gem 'sprockets', '~> 4.1'
gem 'coffee-script', '~> 2.2.0'
gem 'haml', '~> 5.0'
gem 'sass', '~> 3.7'

# utility
gem 'uuid', '~> 2.3.7'
gem 'systemu', '~> 2.5.2'
gem 'bio', '~> 2.0.6'

# development
#gem 'shotgun', '~> 0.9.7'
gem 'rerun', '~> 0.14'       # automatic code reloading for modern Rack/Sinatra
gem 'better_errors', '~> 2.10.1'
gem 'binding_of_caller', '~> 0.8.0'

# development
gem 'webrick', '~> 1.8'

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'nokogiri'
end
